---
title: "project1"
author: "Peter Gray"
date: "3/25/2020"
output: html_document
---

```{r setup, include=FALSE}
library(readxl)
library(ggplot2)
housing <- read_xlsx("~/Stats2/projects/prjoect1/Peter-Gray-Stt-3851/Housing.xlsx")
```



```{r Data Summary and Exploratory Data Analysis}
summary(housing)
pairs(housing[2:8])

par(mfrow = c(2,2))
lm1 <- lm(housing$price ~ housing$lot  + housing$bedrooms) 
summary(lm1)
plot(lm1)
ggplot(housing, aes(x = lot, y = price)) +
  geom_point(shape =2) + 
  geom_smooth()
```

```{r no78}
housing2 <- housing[-74,]
lm2 <- lm(housing2$price ~ housing2$lot  + housing2$bedrooms) 
summary(lm2)
plot(lm2)

```


```{r natural log}
housing$newPrice = log(housing$price)
par(mfrow = c(2,2))
lm3 <- lm(housing$newPrice ~ housing$size  + housing$bedrooms) 
summary(lm3)
plot(lm3)
ggplot(housing, aes(x = bedrooms, y = newPrice)) +
  geom_point(shape =2)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
